apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/OWNER/civicpulse-backend
  newTag: production
- name: ghcr.io/OWNER/civicpulse-frontend
  newTag: production
